apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    metadata:
      name: example-job
      annotations:
        argocd.argoproj.io/hook: PostSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
    spec:
      containers:
      - name: example-container
        image: busybox:latest
        command: ["echo", "Hello from Kubernetes job!"]
      restartPolicy: Never
