apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlapp1.fullname" . }}
  labels:
    {{- include "mlapp1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} 
      protocol: TCP
      name: mlflow
  selector:
    {{- include "mlapp1.selectorLabels" . | nindent 4 }}
